package com.swisscom.aem.tools.jcrhopper.config;

import org.slf4j.Marker;

/**
 * Interface for a listener that gets notified of events that happen during the script run.
 * <p>
 * The evens can be: string output, log output or file output
 */
public interface RunHandler {
	/**
	 * A file has been generated by the script.
	 *
	 * @param file the file that has been generated
	 */
	void file(File file);

	/**
	 * A log message has been generated by the script.
	 * <p>
	 * Log messages are already filtered according to the script’s log level.
	 *
	 * @param level   the level of the log message
	 * @param message the log message itself
	 * @param marker  the marker that was passed to the log call or null if the log call was unmarked
	 */
	void log(LogLevel level, String message, Marker marker);

	/**
	 * Plain text output has been generated by the script.
	 *
	 * @param message the text that was output
	 */
	void print(String message);
}
